name: Production Deployment

on:
  push:
    branches:
      - main
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true


permissions:
  id-token: write
  contents: read    

jobs:
  UpdateCloudformationStacks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050056586:role/RoleForGithubActions
          role-session-name: SessionGithubActionsDeployApwestProdWorkflow
          aws-region: ap-south-1
      
      - name: Install cfn-lint
        run: |
          python3 -m pip install --upgrade pip
          pip install cfn-lint
      
      - name: Deploy stacks
        env:
          AWS_DEFAULT_REGION: ap-south-1
        run: |
          DRY_RUN=false ./infra/deploy.sh